version: '3'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./:/app  
      - /app/node_modules  
    env_file:
      - .env
    depends_on:
      - db
    environment:
      - CHOKIDAR_USEPOLLING=true 

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=huyUW
      - POSTGRES_PASSWORD=huyUW123
      - POSTGRES_DB=dome_db
    ports:
      - "5432:5432"
    volumes:
      - ./data:/docker-entrypoint-initdb.d